use_frameworks!

target 'Heidi' do

pod 'Alamofire', '~> 3.4'
pod 'LKAlertController', '~> 1.6'
pod 'UberRides'
pod 'paper-onboarding'
pod 'ImageLoader'


plugin 'cocoapods-keys', {
  :project => 'Heidi',
  :keys => [
    "UberClientID"
  ]
}

end

